### ISSUE TITLE
Word Audio Not Being Generated

### ISSUE THREAD

**Issue by kraiyt** [DillonWall/generate-batch-audio-anki-addon#17]
In short, I have tried the extension on both qt5 and qt6 versions of anki, Windows 11 & Arch, and with the filter kana, duplicate to empty field, and dangerously fast in different configurations. Sometimes, it will generate one word's audio and then never generate it again (Windows 11) and on Arch it never generated any audio. 

I also confirmed that the word (陰々滅々) was in the local audio server and that yomitan was able to access it. (MoeWay addon: 1045800357) 

I have a feeling that its a simple fix, and I'm doing something wrong.

Thanks in advance!

**Comment by DillonWall** [comment]
Hello and thanks for using the add-on!

Before I try testing things out I'd like to get a bit more information if you don't mind.
- First, how many cards are you trying to add audio to when this issue occurs? 
- Is 陰々滅々 just one of your cards among multiple?
- If so, please give a few more example words (maybe 5 or so) so I can try to reproduce the issue on my own.
- Lastly, please send your list of URLs so I can confirm these are formatted correctly.

It sounds like this may not be the case, but one thing I should note is that the URL should return (only) an audio file after replacing the fields with their correct values. You should be able to test this by manually replacing the fields in the URL and entering it in your browser. If it returns just an audio clip, then the URL should be okay.

**Comment by kraiyt** [comment]
Sorry for the late response. 

I usually generate 30-50 at a time. Sometimes I'll do 3-5 or individual if I notice the note is missing audio/tagged missing media.

Some other words: 
注目の的 
鉄条
印象操作 
破局
補佐官

List of URLs used in the addon

- > http://127.0.0.1:5050/?sources=shinmeikai8&term={word}&reading={reading}
- > http://localhost:5050/?sources=nhk16&term={term}&reading={reading}
- > http://127.0.0.1:5050/?sources=forvo&term={word}&reading={reading}
- > http://127.0.0.1:8770/?expression={word}&reading={reading}
- > http://127.0.0.1:5050/?sources=jpod&term={word}&reading={reading}
- > http://127.0.0.1:5050/?sources=jpod_alternate&term={word}&reading={reading}
- > https://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kanji={word}&kana={reading}

For URLs when they're typed into a web browser:
http://127.0.0.1:5050/?sources=shinmeikai8&term=破局&kana=はきょく  

returns

{"type": "audioSourceList", "audioSources": [{"name": "SMK8 \u30cf\u30ad\u30e7\u30af [0]", "url": "http://localhost:5050/shinmeikai8/media\\08982.mp3"}]}

PC Settings: 

![スクリーンショット 2024-03-06 225324](https://github.com/DillonWall/generate-batch-audio-anki-addon/assets/144865689/2a2b2db6-9735-4b66-9304-6d520f0d2bd5)

**Comment by DillonWall** [comment]
Thank you for your reply, I found a bug with the code in regard to your problem. I will fix this and release a new version today. Please download this new version once I release it and we can see if it solves the issue, I'll post another comment on this issue when it is done. Thanks!

**Comment by DillonWall** [comment]
Okay, I released a new version! Please try updating the addon via the app as normal and try generating audio for your problem cards once more. If all is good, please let me know and I'll close this issue 👍

**Comment by kraiyt** [comment]
Alright, thanks a lot! I tried it out and it seems to be working. Thank you for your time!
