### ISSUE TITLE
Add-on failed to load on Anki 2.1.44

### ISSUE THREAD

**Issue by Botje212** [DillonWall/generate-batch-audio-anki-addon#3]
I installed the addon an restarted Anki, and this came up. 
![image](https://user-images.githubusercontent.com/117949647/230583209-fe5089c1-ed71-47be-8f5c-e745cab47726.png)
Is this something you can help me with?

**Comment by DillonWall** [comment]
I did some quick research into the 'aqt.operations' module in Anki and it appears to me that it was added starting in version 2.1.45, whereas you are running exactly 1 version prior. Therefore, I would assume this error would occur for everyone using versions 2.1.44 and earlier.
For now, I will go ahead and update the docs to say that only versions 2.1.45+ are supported. 

Would you be willing to update your Anki, or do you perhaps have a reason for staying on the 2.1.44 version?

**Comment by Botje212** [comment]
I stayed at 2.1.44 for a long time because I had so many addons plugged into Anki and I'm afraid of updating it due to my infamiliarity as to how things work and what to do in case sth goes wrong

Examples were:
- what things to backup (backed up my Anki2 folder with useless profiles. The Program Files folder without even knowing that I'd installed Anki 2.1.54 there  and Anki 2.1.44 on my desktop. ) 
- downgrading and upgrading profiles seemed mysterious in that I needed to downgrade each time I accidentally opened it with a newer Anki version, 
- wondering whether my settings stay the same with addons like Straight Reward in deck options or tweaked config.json settings - that's sth I'm still unsure of. 
https://addon-docs.ankiweb.net/addon-config.html
(it seems like what's written in the docs,  isn't the case for me, except "Custom Background Image and Gear Icon" which needs to be reconfigured for some reason.)

I searched the Anki forums and manual, but I felt they didn't help me in making sense to what had to be done.
So yeah I'm really afraid of messing things up. And those addons didn't help in gaining this confidence.   

It took a long time for me to go thru all this, I figured out that I could launch Anki on another place (alas a peace of mind), in this way using different Anki2 folders that keep sticking to their own versions and then went ahead to update my Anki to 2.1.49 using the normal upgrade/downgrade method.  The batch audio generator works now.

There's one thing though, the shortcut clashes with this addon https://ankiweb.net/shared/info/291119185 Ctrl+Alt+B. Is there any way to change this?

**Comment by DillonWall** [comment]
Oh nice, I am glad that you were able to figure out a method to safely upgrade Anki; I know it can be stressful when your whole profile is on the line!

As for the shortcut, it is set in code in the main.py file on line 466. As a temporary fix, if you know what you're doing, you could edit this in your personal install of the addon, swapping it with your desired key combo. However, keep in mind this will likely override your change every time the addon has an update. 

For a long term fix, I will look into making this key combo configurable within the addon's config settings.

**Comment by DillonWall** [comment]
I went ahead and opened a new issue for this shortcut topic. I will go ahead and close this current issue as unplanned for now.
